image: gitpod/workspace-full-vnc
ports:
  - name: VNC
    port: 6080
    onOpen: open-browser
tasks:
  - before: |
      DISTRO=humble && sudo apt update && sudo apt install -y curl gnupg lsb-release software-properties-common && sudo add-apt-repository universe -y && \
      sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null && \
      sudo apt update && sudo apt upgrade -y && sudo apt install -y ros-${DISTRO}-desktop python3-argcomplete ros-dev-tools python3-colcon-common-extensions &&  \
      echo "source /opt/ros/${DISTRO}/setup.bash" >> ~/.bashrc && source ~/.bashrc && \
      sudo apt install -y gazebo ros-${DISTRO}-gazebo-* ros-${DISTRO}-joint-state-publisher* && \
      pyenv global system && \
      pip install empy catkin_pkg lark numpy xacro lxml && colcon build && \
      echo "source /workspace/gazebo-ros2-template/install/setup.bash" >> ~/.bashrc && source ~/.bashrc